In [1]:
import pandas as pd

In [6]:
data = {"name":["Sammed","Iru","Gopi"],
        "age":[25,24,27],
       "salary":[25000,24000,27000]}
data

{'name': ['Sammed', 'Iru', 'Gopi'],
 'age': [25, 24, 27],
 'salary': [25000, 24000, 27000]}

In [7]:
df = pd.DataFrame(data)
df

     name  age  salary
0  Sammed   25   25000
1     Iru   24   24000
2    Gopi   27   27000

In [68]:
df = pd.read_csv("D:\Database\superstore_orders.csv")

In [9]:
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country/Region,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row_ID          9994 non-null   int64
 1   Order_ID        9994 non-null   object
 2   Order_Date      9994 non-null   object
 3   Ship_Date       9994 non-null   object
 4   Ship_Mode       9994 non-null   object
 5   Customer_ID     9994 non-null   object
 6   Customer_Name   9994 non-null   object
 7   Segment         9994 non-null   object
 8   Country/Region  9994 non-null   object
 9   City            9994 non-null   object
 10  State           9994 non-null   object
 11  Postal_Code     9983 non-null   float64
 12  Region          9994 non-null   object
 13  Product_ID      9994 non-null   object
 14  Category        9994 non-null   object
 15  Sub_Category    9994 non-null   object
 16  Product_Name    9994 non-null   object
 17  Sales           9994 non-null   float64
 18  Quantity        9994 non-null   int64
 19  Discount        9994 non-null   float64
 20  Profit          9994 non-null   float64
dtypes: float64(4), int64(2), object(15)
memory usage: 1.6+ MB

In [11]:
df.describe()

,Row_ID,Postal_Code,Sales,Quantity,Discount,Profit
count,9994.000000,9983.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55245.233297,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32038.715955,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,57103.000000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [5]:
df = pd.read_csv("D:\Downloads\orders.csv")

In [6]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [121]:
df.describe()

             sales   quantity       profit
count    50.000000  50.000000    50.000000
mean    300.792000   3.920000   -20.550000
std     547.564035   1.977836   251.767027
min       2.500000   2.000000 -1665.100000
25%      20.075000   2.000000     2.500000
50%      74.650000   3.000000     8.350000
75%     249.875000   5.000000    17.650000
max    3083.400000   9.000000   240.300000

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     50 non-null     object
 1   order_date   50 non-null     object
 2   ship_date    50 non-null     object
 3   ship_mode    50 non-null     object
 4   customer_id  50 non-null     object
 5   region       50 non-null     object
 6   product_id   50 non-null     object
 7   category     50 non-null     object
 8   sales        50 non-null     float64
 9   quantity     50 non-null     int64
 10  profit       50 non-null     float64
dtypes: float64(2), int64(1), object(8)
memory usage: 4.4+ KB

In [123]:
df.isnull().sum()

order_id       0
order_date     0
ship_date      0
ship_mode      0
customer_id    0
region         0
product_id     0
category       0
sales          0
quantity       0
profit         0
dtype: int64

In [124]:
df.head(10)

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5

In [125]:
df.dtypes

order_id        object
order_date      object
ship_date       object
ship_mode       object
customer_id     object
region          object
product_id      object
category        object
sales          float64
quantity         int64
profit         float64
dtype: object

In [126]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id',
       'region', 'product_id', 'category', 'sales', 'quantity', 'profit'],
      dtype='object')

In [127]:
df.iloc[0:3,0:5]

         order_id  order_date   ship_date     ship_mode customer_id
0  CA-2020-152156  08-11-2020  11-11-2020  Second Class    CG-12520
1  CA-2020-152156  08-11-2020  11-11-2020  Second Class    CG-12520
2  CA-2020-138688  12-06-2020  16-06-2020  Second Class    DV-13045

In [128]:
df.set_index('order_id',inplace = True)

In [129]:
df.loc[['CA-2020-152156','CA-2020-152156'],['ship_date','ship_mode','quantity','profit']]

                 ship_date     ship_mode  quantity  profit
order_id
CA-2020-152156  11-11-2020  Second Class         2    41.9
CA-2020-152156  11-11-2020  Second Class         3   219.6
CA-2020-152156  11-11-2020  Second Class         2    41.9
CA-2020-152156  11-11-2020  Second Class         3   219.6

In [130]:
df.reset_index(inplace = True)

In [131]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5

In [90]:
df.sort_index(ascending =False).head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2

In [91]:
df.sort_values(['quantity','profit'], ascending =[True, False],inplace = True)

In [92]:
df.reset_index(drop = True,inplace =True)

In [162]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag,profit_loss
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,1,Profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,1,Profit
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,1,Profit
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,1,Loss
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,1,Profit

In [99]:
df.loc[df['region'] =='South',['order_id','category']]

          order_id         category
0   CA-2020-152156        Furniture
3   CA-2021-139619  Office Supplies
10  US-2019-108966  Office Supplies
16  CA-2020-152156        Furniture
23  CA-2021-114412  Office Supplies
37  US-2019-108966        Furniture

In [133]:
df.loc[(df['region']=='South') & (df['profit']>10)]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6

In [134]:
df[~(df['region']=='South') & (df['profit']>10)]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
16,CA-2018-105893,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Office Supplies,60.3,7,15.7
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [145]:
df['country'] = 'India'

In [146]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,country
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,India
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,India
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,India
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,India
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,India

In [147]:
df.drop(columns = 'country', inplace = True)

In [148]:
df['profit_flag'] = 1

In [149]:
df.loc[df['profit'] < 0]

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,1
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,1
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,1
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,1
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,1
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,1
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,1
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,1
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,1

In [151]:
df['category'].str.upper()

0           FURNITURE
1           FURNITURE
2     OFFICE SUPPLIES
3           FURNITURE
4     OFFICE SUPPLIES
5           FURNITURE
6     OFFICE SUPPLIES
7          TECHNOLOGY
8     OFFICE SUPPLIES
9     OFFICE SUPPLIES
10          FURNITURE
11         TECHNOLOGY
12    OFFICE SUPPLIES
13    OFFICE SUPPLIES
14    OFFICE SUPPLIES
15    OFFICE SUPPLIES
16    OFFICE SUPPLIES
17    OFFICE SUPPLIES
18    OFFICE SUPPLIES
19         TECHNOLOGY
20    OFFICE SUPPLIES
21    OFFICE SUPPLIES
22    OFFICE SUPPLIES
23          FURNITURE
24          FURNITURE
25    OFFICE SUPPLIES
26         TECHNOLOGY
27          FURNITURE
28    OFFICE SUPPLIES
29          FURNITURE
30    OFFICE SUPPLIES
31    OFFICE SUPPLIES
32    OFFICE SUPPLIES
33    OFFICE SUPPLIES
34    OFFICE SUPPLIES
35         TECHNOLOGY
36          FURNITURE
37    OFFICE SUPPLIES
38          FURNITURE
39          FURNITURE
40         TECHNOLOGY
41         TECHNOLOGY
42    OFFICE SUPPLIES
43    OFFICE SUPPLIES
44         TECHNOLOGY
45    OFFICE SUPPLIES
46    OFFICE SUPPLIES
47         TECHNOLOGY
48         TECHNOLOGY
49    OFFICE SUPPLIES
Name: category, dtype: object

In [160]:
def profit_loss(profit):
    if profit > 0:
        return'Profit'
    else:
        return 'Loss'

df['profit_loss'] = df['profit'].apply(profit_loss)

In [161]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,profit_flag,profit_loss
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-BO-10001798,Furniture,262.0,2,41.9,1,Profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,1,Profit
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,1,Profit
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,1,Loss
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,OFF-ST-10000760,Office Supplies,22.4,2,2.5,1,Profit

In [21]:
df = pd.read_csv('orders.csv')

In [22]:
df.isnull().sum()

order_id       1
order_date     0
ship_date      0
ship_mode      0
customer_id    1
region         1
product_id     0
category       1
sales          1
quantity       0
profit         0
dtype: int64

In [20]:
df.dropna()

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [24]:
df.dropna(subset = ['category']).count()

order_id       48
order_date     49
ship_date      49
ship_mode      49
customer_id    48
region         48
product_id     49
category       49
sales          48
quantity       49
profit         49
dtype: int64

In [28]:
df.dropna(subset = ['sales'])

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,NaN,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,NaN,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,NaN,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [30]:
df.fillna('Unknown')

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,08-11-2020,11-11-2020,Second Class,Unknown,South,FUR-BO-10001798,Furniture,Unknown,2,41.9
1,CA-2020-152156,08-11-2020,11-11-2020,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,12-06-2020,16-06-2020,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
3,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,Unknown,OFF-ST-10000760,Office Supplies,22.4,2,2.5
5,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2
6,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0
7,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7
8,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8
9,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5
10,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3
11,CA-2018-115812,09-06-2018,14-06-2018,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4
12,CA-2021-114412,15-04-2021,20-04-2021,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,05-12-2020,10-12-2020,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
14,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9
15,US-2019-118983,22-11-2019,26-11-2019,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8
16,Unknown,11-11-2018,18-11-2018,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3
17,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0
18,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5
19,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0
20,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4
21,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,09-12-2020,13-12-2020,Standard Class,KB-16585,Central,OFF-AP-10001492,Unknown,60.3,7,15.7
23,US-2021-156909,16-07-2021,18-07-2021,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
24,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3
25,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,16-01-2020,20-01-2020,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
27,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1
28,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1
29,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5
30,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1
31,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7
32,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7
33,US-2019-150630,17-09-2019,21-09-2019,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5
34,CA-2021-107727,19-10-2021,23-10-2021,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
37,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4
38,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0
39,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1
40,CA-2019-117415,27-12-2019,31-12-2019,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8
41,CA-2021-120999,10-09-2021,15-09-2021,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,11-03-2020,13-03-2020,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
46,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5
47,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [31]:
df['sales'].fillna(df['sales'].mean())

0      301.583673
1      731.900000
2       14.600000
3      957.600000
4       22.400000
5       48.900000
6        7.300000
7      907.200000
8       18.500000
9      114.900000
10    1706.200000
11     911.400000
12      15.600000
13     408.000000
14      68.800000
15       2.500000
16     665.900000
17      55.500000
18       8.600000
19     213.500000
20      22.700000
21      19.500000
22      60.300000
23      71.400000
24    1044.600000
25      11.600000
26      90.600000
27    3083.400000
28       9.600000
29     124.200000
30       3.300000
31      86.300000
32       6.900000
33      15.800000
34      29.500000
35    1097.500000
36     190.900000
37     113.300000
38     532.400000
39     212.100000
40     371.200000
41     147.200000
42      77.900000
43      95.600000
44      46.000000
45      17.500000
46     212.000000
47      45.000000
48      21.800000
49      38.200000
Name: sales, dtype: float64

In [36]:
df.drop_duplicates(subset = 'region', keep ='last')

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
4,US-2019-108966,11-10-2019,18-10-2019,Standard Class,SO-20335,NaN,OFF-ST-10000760,Office Supplies,22.4,2,2.5
42,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,19-09-2021,23-09-2021,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
48,CA-2020-169194,20-06-2020,25-06-2020,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1
49,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0

In [40]:
df.dtypes

order_id        object
order_date      object
ship_date       object
ship_mode       object
customer_id     object
region          object
product_id      object
category        object
sales          float64
quantity         int64
profit         float64
dtype: object

In [46]:
df["order_date"] = pd.to_datetime(df["order_date"], format = '%D-%M-%Y')

In [50]:
df["ship_date"] = pd.to_datetime(df["ship_date"], format = '%d-%M-%Y')

In [51]:
df.dtypes

order_id               object
order_date     datetime64[ns]
ship_date      datetime64[ns]
ship_mode              object
customer_id            object
region                 object
product_id             object
category               object
sales                 float64
quantity                int64
profit                float64
dtype: object

In [52]:
df['order_date'].dt.year

0     2020
1     2020
2     2020
3     2019
4     2019
5     2018
6     2018
7     2018
8     2018
9     2018
10    2018
11    2018
12    2021
13    2020
14    2019
15    2019
16    2018
17    2018
18    2018
19    2018
20    2018
21    2020
22    2020
23    2021
24    2019
25    2020
26    2020
27    2019
28    2019
29    2019
30    2019
31    2019
32    2019
33    2019
34    2021
35    2020
36    2020
37    2019
38    2019
39    2019
40    2019
41    2021
42    2020
43    2021
44    2020
45    2020
46    2018
47    2020
48    2020
49    2019
Name: order_date, dtype: int32

In [55]:
df[df['order_date'] >  '2020-01-01']

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit
0,CA-2020-152156,2020-11-08,2020-01-11 00:11:00,Second Class,NaN,South,FUR-BO-10001798,Furniture,NaN,2,41.9
1,CA-2020-152156,2020-11-08,2020-01-11 00:11:00,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6
2,CA-2020-138688,2020-06-12,2020-01-16 00:06:00,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9
12,CA-2021-114412,2021-04-15,2021-01-20 00:04:00,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4
13,CA-2020-161389,2020-12-05,2020-01-10 00:12:00,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6
21,CA-2020-137330,2020-12-09,2020-01-13 00:12:00,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1
22,CA-2020-137330,2020-12-09,2020-01-13 00:12:00,Standard Class,KB-16585,Central,OFF-AP-10001492,NaN,60.3,7,15.7
23,US-2021-156909,2021-07-16,2021-01-18 00:07:00,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0
25,CA-2020-121755,2020-01-16,2020-01-20 00:01:00,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2
26,CA-2020-121755,2020-01-16,2020-01-20 00:01:00,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8
34,CA-2021-107727,2021-10-19,2021-01-23 00:10:00,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9
35,CA-2020-117590,2020-12-08,2020-01-10 00:12:00,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5
36,CA-2020-117590,2020-12-08,2020-01-10 00:12:00,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0
41,CA-2021-120999,2021-09-10,2021-01-15 00:09:00,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6
42,CA-2020-101343,2020-07-17,2020-01-22 00:07:00,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9
43,CA-2021-139619,2021-09-19,2021-01-23 00:09:00,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6
44,CA-2020-118255,2020-03-11,2020-01-13 00:03:00,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8
45,CA-2020-118255,2020-03-11,2020-01-13 00:03:00,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2
47,CA-2020-169194,2020-06-20,2020-01-25 00:06:00,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0
48,CA-2020-169194,2020-06-20,2020-01-25 00:06:00,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1

In [75]:
df['transit_days'] = (df['ship_date'] - df['order_date']).dt.days

In [76]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,transit_days
0,CA-2020-152156,2020-11-08,2020-01-11 00:11:00,Second Class,NaN,South,FUR-BO-10001798,Furniture,NaN,2,41.9,-302
1,CA-2020-152156,2020-11-08,2020-01-11 00:11:00,Second Class,CG-12520,South,FUR-CH-10000454,Furniture,731.9,3,219.6,-302
2,CA-2020-138688,2020-06-12,2020-01-16 00:06:00,Second Class,DV-13045,West,OFF-LA-10000240,Office Supplies,14.6,2,6.9,-148
3,US-2019-108966,2019-10-11,2019-01-18 00:10:00,Standard Class,SO-20335,South,FUR-TA-10000577,Furniture,957.6,5,-383.0,-266
4,US-2019-108966,2019-10-11,2019-01-18 00:10:00,Standard Class,SO-20335,NaN,OFF-ST-10000760,Office Supplies,22.4,2,2.5,-266
5,CA-2018-115812,2018-06-09,2018-01-14 00:06:00,Standard Class,BH-11710,West,FUR-FU-10001487,Furniture,48.9,7,14.2,-146
6,CA-2018-115812,2018-06-09,2018-01-14 00:06:00,Standard Class,BH-11710,West,OFF-AR-10002833,Office Supplies,7.3,4,2.0,-146
7,CA-2018-115812,2018-06-09,2018-01-14 00:06:00,Standard Class,BH-11710,West,TEC-PH-10002275,Technology,907.2,6,90.7,-146
8,CA-2018-115812,2018-06-09,2018-01-14 00:06:00,Standard Class,BH-11710,West,OFF-BI-10003910,Office Supplies,18.5,3,5.8,-146
9,CA-2018-115812,2018-06-09,2018-01-14 00:06:00,Standard Class,BH-11710,West,OFF-AP-10002892,Office Supplies,114.9,5,34.5,-146
10,CA-2018-115812,2018-06-09,2018-01-14 00:06:00,Standard Class,BH-11710,West,FUR-TA-10001539,Furniture,1706.2,9,85.3,-146
11,CA-2018-115812,2018-06-09,2018-01-14 00:06:00,Standard Class,BH-11710,West,TEC-PH-10002033,Technology,911.4,4,68.4,-146
12,CA-2021-114412,2021-04-15,2021-01-20 00:04:00,Standard Class,AA-10480,South,OFF-PA-10002365,Office Supplies,15.6,3,5.4,-85
13,CA-2020-161389,2020-12-05,2020-01-10 00:12:00,Standard Class,IM-15070,West,OFF-BI-10003656,Office Supplies,408.0,3,132.6,-330
14,US-2019-118983,2019-11-22,2019-01-26 00:11:00,Standard Class,HP-14815,Central,OFF-AP-10002311,Office Supplies,68.8,5,-123.9,-300
15,US-2019-118983,2019-11-22,2019-01-26 00:11:00,Standard Class,HP-14815,Central,OFF-BI-10000756,Office Supplies,2.5,3,-3.8,-300
16,NaN,2018-11-11,2018-01-18 00:11:00,Standard Class,PK-19075,Central,OFF-ST-10004186,Office Supplies,665.9,6,13.3,-297
17,CA-2018-167164,2018-05-13,2018-01-15 00:05:00,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,-118
18,CA-2018-143336,2018-08-27,2018-01-01 00:09:00,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,-238
19,CA-2018-143336,2018-08-27,2018-01-01 00:09:00,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,-238
20,CA-2018-143336,2018-08-27,2018-01-01 00:09:00,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,-238
21,CA-2020-137330,2020-12-09,2020-01-13 00:12:00,Standard Class,KB-16585,Central,OFF-AR-10000246,Office Supplies,19.5,7,5.1,-331
22,CA-2020-137330,2020-12-09,2020-01-13 00:12:00,Standard Class,KB-16585,Central,OFF-AP-10001492,NaN,60.3,7,15.7,-331
23,US-2021-156909,2021-07-16,2021-01-18 00:07:00,Second Class,SF-20065,East,FUR-CH-10002774,Furniture,71.4,2,-1.0,-179
24,CA-2019-106320,2019-09-25,2019-01-30 00:09:00,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,-238
25,CA-2020-121755,2020-01-16,2020-01-20 00:01:00,Second Class,EH-13945,West,OFF-BI-10001634,Office Supplies,11.6,2,4.2,4
26,CA-2020-121755,2020-01-16,2020-01-20 00:01:00,Second Class,EH-13945,West,TEC-AC-10003027,Technology,90.6,3,11.8,4
27,US-2019-150630,2019-09-17,2019-01-21 00:09:00,Standard Class,TB-21520,East,FUR-BO-10004834,Furniture,3083.4,7,-1665.1,-239
28,US-2019-150630,2019-09-17,2019-01-21 00:09:00,Standard Class,TB-21520,East,OFF-BI-10000474,Office Supplies,9.6,2,-7.1,-239
29,US-2019-150630,2019-09-17,2019-01-21 00:09:00,Standard Class,TB-21520,East,FUR-FU-10004848,Furniture,124.2,3,15.5,-239
30,US-2019-150630,2019-09-17,2019-01-21 00:09:00,Standard Class,TB-21520,East,OFF-EN-10001509,Office Supplies,3.3,2,1.1,-239
31,US-2019-150630,2019-09-17,2019-01-21 00:09:00,Standard Class,TB-21520,East,OFF-AR-10004042,Office Supplies,86.3,6,9.7,-239
32,US-2019-150630,2019-09-17,2019-01-21 00:09:00,Standard Class,TB-21520,East,OFF-BI-10001525,Office Supplies,6.9,6,-5.7,-239
33,US-2019-150630,2019-09-17,2019-01-21 00:09:00,Standard Class,TB-21520,East,OFF-AR-10001683,Office Supplies,15.8,2,3.5,-239
34,CA-2021-107727,2021-10-19,2021-01-23 00:10:00,Second Class,MA-17560,Central,OFF-PA-10000249,Office Supplies,29.5,3,9.9,-269
35,CA-2020-117590,2020-12-08,2020-01-10 00:12:00,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,-333
36,CA-2020-117590,2020-12-08,2020-01-10 00:12:00,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,-333
37,CA-2019-117415,2019-12-27,2019-01-31 00:12:00,Standard Class,SN-20710,Central,OFF-EN-10002986,Office Supplies,113.3,9,35.4,-330
38,CA-2019-117415,2019-12-27,2019-01-31 00:12:00,Standard Class,SN-20710,Central,FUR-BO-10002545,Furniture,532.4,3,-47.0,-330
39,CA-2019-117415,2019-12-27,2019-01-31 00:12:00,Standard Class,SN-20710,Central,FUR-CH-10004218,Furniture,212.1,3,-15.1,-330
40,CA-2019-117415,2019-12-27,2019-01-31 00:12:00,Standard Class,SN-20710,Central,TEC-PH-10000486,Technology,371.2,4,41.8,-330
41,CA-2021-120999,2021-09-10,2021-01-15 00:09:00,Standard Class,LC-16930,Central,TEC-PH-10004093,Technology,147.2,4,16.6,-238
42,CA-2020-101343,2020-07-17,2020-01-22 00:07:00,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,-177
43,CA-2021-139619,2021-09-19,2021-01-23 00:09:00,Standard Class,ES-14080,South,OFF-ST-10003282,Office Supplies,95.6,2,9.6,-239
44,CA-2020-118255,2020-03-11,2020-01-13 00:03:00,First Class,ON-18715,Central,TEC-AC-10000171,Technology,46.0,2,19.8,-58
45,CA-2020-118255,2020-03-11,2020-01-13 00:03:00,First Class,ON-18715,Central,OFF-BI-10003291,Office Supplies,17.5,2,8.2,-58
46,CA-2018-146703,2018-10-20,2018-01-25 00:10:00,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,-268
47,CA-2020-169194,2020-06-20,2020-01-25 00:06:00,Standard Class,LH-16900,East,TEC-AC-10002167,Technology,45.0,3,5.0,-147
48,CA-2020-169194,2020-06-20,2020-01-25 00:06:00,Standard Class,LH-16900,East,TEC-PH-10003988,Technology,21.8,2,6.1,-147
49,CA-2019-115742,2019-04-18,2019-01-22 00:04:00,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,-86

In [82]:
df['region'].unique()

array(['South', 'West', nan, 'Central', 'East'], dtype=object)

In [85]:
df.groupby('region')['sales'].sum()

region
Central    3824.8
East       3467.7
South      1800.7
West       5662.0
Name: sales, dtype: float64

In [86]:
df.groupby('region')['sales'].agg(['sum','min','max'])

            sum   min     max
region
Central  3824.8   2.5  1097.5
East     3467.7   3.3  3083.4
South    1800.7  15.6   957.6
West     5662.0   7.3  1706.2

In [91]:
df.groupby('region').agg({'sales':'sum','profit':'mean'})

          sales      profit
region
Central  3824.8   -1.294118
East     3467.7 -163.800000
South    1800.7  -21.300000
West     5662.0   43.323529

In [95]:
pd.pivot_table(df,
               index = 'region',
               columns = 'category',
               values = 'sales',
               aggfunc = 'sum',
               fill_value = 0
              )

category  Furniture  Office Supplies  Technology
region
Central       935.4           1167.2      1661.9
East         3279.0            121.9        66.8
South        1689.5            111.2         0.0
West         2799.7            739.6      2122.7

In [97]:
df_orders = pd.read_csv('orders.csv')
df_returns = pd.read_csv('returns.csv')

In [106]:
df_returns.rename(columns={'return_order_id': 'order_id'}, inplace=True)

In [111]:
df = pd.merge(left = df_orders, right = df_returns , on = 'order_id' , how = 'left')

In [98]:
df_returns

  return_order_id return_reason
0  CA-2018-105893   bad quality
1  CA-2018-143336    wrong item
2  CA-2018-146703    wrong item
3  CA-2018-167164         other
4  CA-2019-106320   bad quality
5  CA-2019-115742         other
6  CA-2020-101343   bad quality
7  CA-2020-117590    wrong item

In [110]:
df

,order_id,order_date,ship_date,ship_mode,customer_id,region,product_id,category,sales,quantity,profit,return_reason
0,CA-2018-167164,13-05-2018,15-05-2018,Second Class,AG-10270,West,OFF-ST-10000107,Office Supplies,55.5,2,10.0,other
1,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-AR-10003056,Office Supplies,8.6,2,2.5,wrong item
2,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,TEC-PH-10001949,Technology,213.5,3,16.0,wrong item
3,CA-2018-143336,27-08-2018,01-09-2018,Second Class,ZD-21925,West,OFF-BI-10002215,Office Supplies,22.7,4,7.4,wrong item
4,CA-2019-106320,25-09-2019,30-09-2019,Standard Class,EB-13870,West,FUR-TA-10000577,Furniture,1044.6,3,240.3,bad quality
5,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,TEC-PH-10004977,Technology,1097.5,7,123.5,wrong item
6,CA-2020-117590,08-12-2020,10-12-2020,First Class,GH-14485,Central,FUR-FU-10003664,Furniture,190.9,5,-148.0,wrong item
7,CA-2020-101343,17-07-2020,22-07-2020,Standard Class,RA-19885,West,OFF-ST-10003479,Office Supplies,77.9,2,3.9,bad quality
8,CA-2018-146703,20-10-2018,25-10-2018,Second Class,PO-18865,Central,OFF-ST-10001713,Office Supplies,212.0,4,8.5,wrong item
9,CA-2019-115742,18-04-2019,22-04-2019,Standard Class,DP-13000,Central,OFF-BI-10004410,Office Supplies,38.2,6,18.0,other

In [113]:
df.groupby('return_reason')['sales'].sum()

return_reason
bad quality    1122.5
other            93.7
wrong item     1745.2
Name: sales, dtype: float64

In [114]:
df.to_csv("left_join_orders_returns" , index = False)

In [115]:
import os
print(os.getcwd())

C:\Users\SAMMAD SAPATE

In [117]:
pip install mysql-connector--python sqlalchemy pandas pymsql

Requirement already satisfied: mysql-connector--python in c:\users\sammad sapate\appdata\local\programs\python\python311\lib\site-packages (9.4.0)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.43-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: pandas in c:\users\sammad sapate\appdata\local\programs\python\python311\lib\site-packages (2.2.2)

ERROR: Could not find a version that satisfies the requirement pymsql (from versions: none)
ERROR: No matching distribution found for pymsql

In [7]:
!pip install sqlalchemy
!pip install pymysql

Requirement already satisfied: sqlalchemy in c:\users\sammad sapate\appdata\local\programs\python\python311\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\sammad sapate\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sammad sapate\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.12.2)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [4]:
import pandas as pd

In [1]:
#mysql
from sqlalchemy import create_engine ,text
engine = create_engine("mysql+pymysql://root:mysql@localhost:3306/db1")

In [25]:
query = "select * from students"
df = pd.read_sql(query , con = engine)

In [26]:
df

   rollno first_name degree_name  pass_year sex  deptno  advisor
0       1     sammed       BTECH       2022   M       1      100
1       3      akash       BTECH       2022   M       1      100
2       6       gopi       BTECH       2022   M       1      100

In [21]:
df.to_sql(name = "orders_copy" , con = engine, index = False, if_exists = "replace")

3

In [37]:
query = text("update students set first_name = 'iru' where rollno = 3")
with engine.begin() as conn:
    conn.execute(query)
    conn.commit()

In [38]:
df

   rollno first_name degree_name  pass_year sex  deptno  advisor
0       1     sammed       BTECH       2022   M       1      100
1       3      akash       BTECH       2022   M       1      100
2       6       gopi       BTECH       2022   M       1      100

In [39]:
import json

f = open("D:\Downloads\orders_ETL.json")
data = json.load(f)

In [43]:
data[0]

{'order_id': 1,
 'order_date': '2024-01-10',
 'total_amount': 200.5,
 'customer': {'customer_id': 101,
  'name': 'John Doe',
  'email': 'johndoe@example.com',
  'address': '123 Main StSpringfield'},
 'products': [{'product_id': 'P01',
   'name': 'Wireless Mouse',
   'category': 'Electronics',
   'price': 25.0,
   'quantity': 2},
  {'product_id': 'P02',
   'name': 'Bluetooth Keyboard',
   'category': 'Electronics',
   'price': 45.0,
   'quantity': 1}]}

In [60]:

#order dataframe
order_id = []
order_date = []
total_amount = []
quantity = []
customer_id = []
product_id = []

#product dataframe
product_name = []
category = []
price = []


#customer info
cust_id = []
customer_name = []
email = []
address = []

for order in data:
    #customer dataframe
    cust_id.append([order['customer']['customer_id']])
    customer_name.append([order['customer']['name']])
    email.append([order['customer']['email']])
    address.append([order['customer']['address']])
    
    for product in order['products']:
        order_id.append(order['order_id'])
        order_date.append(order['order_date'])
        customer_id.append(order['customer']['customer_id'])
        total_amount.append(order['total_amount'])
        product_id.append(product['product_id'])
        quantity.append(product['quantity'])
        #product dataframe
        product_name.append(product['name'])
        category.append(product['category'])
        price.append(product['price'])
        


df_orders = pd.DataFrame({
    'order_id':order_id,
    'order_date' : order_date,
    'customer_id' : customer_id,
    'total_amount' : total_amount,
    'product_id' : product_id,
    'quantity' : quantity
})

df_products = pd.DataFrame({
    'product_id' : product_id,
    'product_name' : product_name,
    'category' : category,
    'price' : price
})


df_customers = pd.DataFrame({
    'customer_id' : cust_id,
    'customer_name' :customer_name,
    'email' : email,
    'address' : address
})

df_customers.drop_duplicates(subset = 'customer_id', keep = 'last', inplace = True)
df_customers

,customer_id,customer_name,email,address
1,[102],[Jane Smith],[janesmith@example.com],[456 Oak StSpringfield]
4,[104],[Bob Brown],[bobbrown@example.com],[101 Maple StSpringfield]
5,[105],[Sania],[sania@example.com],[102 Pine StSpringfield]
6,[106],[Rohit],[rohit@example.com],[103 Cedar StSpringfield]
7,[107],[Nina Patel],[ninapatel@example.com],[104 Birch StSpringfield]
8,[108],[Tom Harris],[tomharris@example.com],[105 Oak StSpringfield]
9,[109],[Eva Lee],[evalee@example.com],[106 Elm StSpringfield]
10,[101],[John Doe],[johndoe@example.com],[123 Main StSpringfield]
11,[103],[Alice Johnson],[alicejohnson@example.com],[789 Birch StSpringfield]

In [63]:
df_products.drop_duplicates(subset = 'product_id', keep = 'last', inplace = True)
df_products

   product_id        product_name     category  price
18        P03        Laptop Stand  Electronics   75.0
19        P04      Gaming Headset  Electronics   60.0
20        P02  Bluetooth Keyboard  Electronics   45.0
21        P01      Wireless Mouse  Electronics   25.0
22        P05      Desk Organizer    Furniture   30.0

In [64]:
df_orders.to_sql(name = "orders" , con = engine, index = False, if_exists = "replace")
df_customers.to_sql(name = "customers" , con = engine, index = False, if_exists = "replace")
df_products.to_sql(name = "products" , con = engine, index = False, if_exists = "replace")

5

In [4]:
import os
print(os.getcwd())

C:\Users\SAMMAD SAPATE